import type { Carrier } from "./types";

export const CARRIERS_FIXTURE: Carrier[] = [
  {
    id: "zr-express",
    name: "ZR Express",
    nameAr: "زد أر إكسبرس",
    dashboardUrl: "https://zr-express.com",
    sortedOrder: 1,
    credentialSchema: [
      {
        key: "token",
        label: "الرمز (API Token)",
        type: "password",
        required: true,
        dir: "ltr",
        placeholder: "••••••••",
        hint: "من لوحة تحكم ZR Express",
        help: "ادخل إلى حسابك في ZR Express ثم افتح «الإعدادات» وقسم «API». انسخ قيمة Token وKey كاملة.",
      },
      {
        key: "key",
        label: "المفتاح (API Key)",
        type: "password",
        required: true,
        dir: "ltr",
        placeholder: "••••••••",
        hint: "بجانب الرمز في نفس القسم",
        help: "المفتاح (Key) موجود بجانب الرمز (Token) في نفس صفحة الإعدادات. انسخ الاثنين معاً.",
      },
    ],
  },
  {
    id: "yalidine",
    name: "Yalidine",
    nameAr: "ياليدين",
    dashboardUrl: "https://www.yalidine.dz",
    sortedOrder: 2,
    credentialSchema: [
      {
        key: "apiId",
        label: "معرّف (API ID)",
        type: "text",
        required: true,
        dir: "ltr",
        placeholder: "••••••••",
        hint: "من إعدادات الحساب في Yalidine",
        help: "سجّل الدخول إلى منصة Yalidine ثم «الإعدادات» ← «API». ستجد API ID و API Token.",
      },
      {
        key: "apiToken",
        label: "الرمز (API Token)",
        type: "password",
        required: true,
        dir: "ltr",
        placeholder: "••••••••",
        hint: "مقابل المعرّف",
        help: "انسخ الـ API Token من نفس صفحة الإعدادات التي أخذت منها المعرّف.",
      },
    ],
  },
  {
    id: "maystro",
    name: "Maystro",
    nameAr: "مايسترو",
    dashboardUrl: "https://www.maystro.com",
    sortedOrder: 3,
    credentialSchema: [
      {
        key: "apiKey",
        label: "مفتاح API",
        type: "password",
        required: true,
        dir: "ltr",
        placeholder: "••••••••",
        hint: "حقل واحد فقط يكفي",
        help: "تتطلب Maystro مفتاح API وحيداً. تجده في الإعدادات ← التكامل مع المتاجر.",
      },
    ],
  },
  {
    id: "noest",
    name: "NOEST",
    nameAr: "نويست",
    dashboardUrl: "https://noest.com",
    sortedOrder: 4,
    credentialSchema: [
      {
        key: "apiToken",
        label: "الرمز (API Token)",
        type: "password",
        required: true,
        dir: "ltr",
        placeholder: "••••••••",
        hint: "من لوحة تحكم NOEST",
        help: "ادخل إلى لوحة NOEST ثم «الإعدادات» للحصول على الـ API Token و GUID الخاصين بحسابك.",
      },
      {
        key: "guid",
        label: "المعرّف (GUID)",
        type: "text",
        required: true,
        dir: "ltr",
        placeholder: "••••••••",
        hint: "معرّف حسابك لدى NOEST",
        help: "الـ GUID يميز حسابك. تجده في نفس صفحة الإعدادات بجوار الـ Token.",
      },
    ],
  },
  {
    id: "ecotrack-dhd",
    name: "DHD (Ecotrack)",
    nameAr: "دي إتش دي",
    dashboardUrl: "https://platform.dhd-dz.com",
    sortedOrder: 5,
    credentialSchema: [
      {
        key: "token",
        label: "الرمز (Token)",
        type: "password",
        required: true,
        dir: "ltr",
        placeholder: "••••••••",
        hint: "من بيئة الشركة على Ecotrack",
        help: "ادخل إلى منصة Ecotrack الخاصة بشركتك ثم أنشئ مفتاح API من الإعدادات.",
      },
      {
        key: "baseUrl",
        label: "رابط المنصة",
        type: "url",
        required: true,
        dir: "ltr",
        placeholder: "https://platform.dhd-dz.com",
        hint: "رابط حسابك على المنصة",
        help: "أدخل رابط المنصة الخاص بشركة التوصيل كما يظهر في متصفحك عند الدخول، ويبدأ بـ https://.",
      },
    ],
  },
];